# WRITTEN AND MANAGED BY GW KANG
name: FreeFireRipper

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: windows-latest

    steps:
      - name: Setup
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force output
          Write-Host "Windows siap."

      - name: Check files
        shell: pwsh
        run: |
          Get-ChildItem -Force

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreeFireRipper-output
          path: output
          retention-days: 3
